### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by matkuki** [Vladar4/NimVoxelSpaceDemo#1]
Hi @Vladar4 ,

Compiling throws an error:
```
Hint: system [Processing]
Hint: nvs_demo [Processing]
Hint: math [Processing]
Hint: sdl [Processing]
Hint: sdl_image [Processing]
sdl2\sdl_image.nim(99, 20) template/generic instantiation from here
sdl2\sdl_image.nim(43, 22) template/generic instantiation from here
sdl2\private\version.nim(79, 27) Error: expression '2002' is of type 'int literal(2002)' and has to be discarded
```
I just copied your **sdl2_nim**'s *sdl2* directory into the working directory.

My specs:
- Windows 10 x64
- Nim Compiler Version 0.17.3 (2017-10-07) [Windows: i386]
- gcc (i686-win32-sjlj-rev2, Built by MinGW-W64 project) 7.1.0

**Comment by Vladar4** [comment]
Was discussed [here](https://github.com/Vladar4/sdl2_nim/issues/12). Use the latest version ( nimble install sdl2_nim@#head ), or [v2.0.6.1](https://github.com/Vladar4/sdl2_nim/releases/tag/v2.0.6.1).

Please, let me know if this fixes your problem.

**Comment by matkuki** [comment]
Yup, that fixed it! Thanks.

Looks nice! Reminds me of **Magic Carpet** for MS-DOS.
